# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    access_control:
        - { path: ^/webhook/, roles: ROLE_USER, requires_channel: https }
        - { path: ^/, roles: ROLE_USER  }

