# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    hook:
                        password: '%hook_user_password%'
                        roles: 'ROLE_USER'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        hmac_secured:
            pattern: ^/webhookhmac/incident/
            anonymous: ~
            stateless: true  # HMAC is stateless!
            provider: in_memory
            hmac:
                auth_header: Authorization # Name of the header to inspect
                service_label: LE        # Service name/id
                algorithm: sha1          # Hashing algoritm, see hash_algos()
                verify_headers: ['method','Content-Type','content_md5', 'Date','path', 'X-Le-Nonce']         # Array or comma-separated list of headers


            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        http_basic:
            anonymous: ~
            pattern: ^/
            security: true
            http_basic:
                realm: 'Secured Demo Area'
                provider: in_memory